### ISSUE TITLE
About this repository

### ISSUE THREAD

**Issue by lebron-2016** [mhy9989/CFD-CNN#1]
Hi!

Is there a corresponding paper for the code in your repository? I saw that you implemented the TAU module. Is this the official implementation of the paper (Temporal attention unit: Towards efficient spatiotemporal predictive learning)?

**Comment by mhy9989** [comment]
This repository is based on OpenSTL. You can refer to the original code in the following repository: https://github.com/chengtan9907/OpenSTL

**Comment by lebron-2016** [comment]
> This repository is based on OpenSTL. You can refer to the original code in the following repository: https://github.com/chengtan9907/OpenSTL
OK! Thanks a lot!!

**Comment by lebron-2016** [comment]
> This repository is based on OpenSTL. You can refer to the original code in the following repository: https://github.com/chengtan9907/OpenSTL

OK. Thanks a lot!!
